######################################################################
# Automatically generated by qmake (2.01a) Fri Jun 3 03:39:02 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
CONFIG -= qt
OBJECTS_DIR = obj
LIBS += -lmhash

# Input
HEADERS += aocs.h comms.h power.h rtc.h sim.h rand.h log.h zerog_module.h timesys.h
SOURCES += aocs.c comms.c power.c rtc.c sim.c rand.c log.c zerog_module.c timesys.c
